name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  python-checks:
    name: Python checks (${{ matrix.service }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [gateway, market, simulator, portfolio, stats, ml, explain]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: services/${{ matrix.service }}
        run: |
          python -m pip install --upgrade pip
          pip install -e . pytest

      - name: Run placeholder linter
        working-directory: services/${{ matrix.service }}
        run: |
          echo "TODO: replace with real lint command for ${{ matrix.service }}"

      - name: Run pytest (non-blocking)
        working-directory: services/${{ matrix.service }}
        run: |
          pytest -q || true

  docker-build:
    name: Docker build (${{ matrix.service }})
    runs-on: ubuntu-latest
    needs: python-checks
    strategy:
      matrix:
        service: [gateway, market, simulator, portfolio, stats, ml, explain]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build service image
        run: |
          docker build -t quantisti-${{ matrix.service }}:ci ./services/${{ matrix.service }}
